const simpleImportSort = require(`eslint-plugin-simple-import-sort`),
	pluginVue = require(`eslint-plugin-vue`),
	wordpress = require(`@wordpress/eslint-plugin`),
	eslintConfigPrettier = require(`eslint-config-prettier/flat`),
	js = require(`@eslint/js`),
	globals = require(`globals`);

module.exports = [
	{
		ignores: [`build/**`, `vendor/**`],
	},
	...pluginVue.configs[`flat/recommended`],
	...wordpress.configs.esnext,
	...wordpress.configs.custom,
	{
		languageOptions: {
			globals: {
				...globals.browser,
			},
		},
		plugins: {
			'simple-import-sort': simpleImportSort,
			vue: pluginVue,
		},
		rules: {
			...js.configs.recommended.rules,
			'accessor-pairs': `error`,
			'array-callback-return': `error`,
			'arrow-body-style': [`error`, `as-needed`],
			'block-scoped-var': `error`,
			'class-methods-use-this': `error`,
			'consistent-this': [`error`, `self`],
			'default-param-last': `error`,
			'dot-notation': `error`,
			eqeqeq: `error`,
			'func-name-matching': `error`,
			'func-style': [
				`error`,
				`declaration`,
				{
					allowArrowFunctions: true,
				},
			],
			'grouped-accessor-pairs': `error`,
			'guard-for-in': `error`,
			'handle-callback-err': `error`,
			'init-declarations': `error`,
			'line-comment-position': `error`,
			'lines-between-class-members': `error`,
			'max-classes-per-file': `error`,
			'max-depth': `error`,
			'max-nested-callbacks': `error`,
			'max-params': `error`,
			'multiline-comment-style': [`error`, `separate-lines`],
			'new-cap': `error`,
			'no-alert': `error`,
			'no-array-constructor': `error`,
			'no-await-in-loop': `error`,
			'no-bitwise': `error`,
			'no-buffer-constructor': `error`,
			'no-caller': `error`,
			'no-case-declarations': `off`,
			'no-console': `error`,
			'no-constructor-return': `error`,
			'no-div-regex': `error`,
			'no-duplicate-imports': `error`,
			'no-else-return': `error`,
			'no-empty-function': `error`,
			'no-eq-null': `error`,
			'no-eval': `error`,
			'no-extend-native': `error`,
			'no-extra-bind': `error`,
			'no-implicit-coercion': `error`,
			'no-implicit-globals': `error`,
			'no-implied-eval': `error`,
			'no-inline-comments': `error`,
			'no-invalid-this': `error`,
			'no-iterator': `error`,
			'no-label-var': `error`,
			'no-lone-blocks': `error`,
			'no-lonely-if': `error`,
			'no-loop-func': `error`,
			'no-mixed-requires': `error`,
			'no-multi-assign': `error`,
			'no-multi-str': `error`,
			'no-negated-condition': `error`,
			'no-nested-ternary': `error`,
			'no-new-func': `error`,
			'no-new-object': `error`,
			'no-new-require': `error`,
			'no-new-wrappers': `error`,
			'no-octal-escape': `error`,
			'no-param-reassign': `error`,
			'no-path-concat': `error`,
			'no-process-env': `error`,
			'no-process-exit': `error`,
			'no-proto': `error`,
			'no-prototype-builtins': `off`,
			'no-restricted-globals': `error`,
			'no-restricted-imports': `error`,
			'no-restricted-modules': `error`,
			'no-restricted-properties': `error`,
			'no-return-assign': `error`,
			'no-return-await': `error`,
			'no-script-url': `error`,
			'no-self-compare': `error`,
			'no-sequences': `error`,
			'no-shadow': `error`,
			'no-template-curly-in-string': `error`,
			'no-throw-literal': `error`,
			'no-undef-init': `error`,
			'no-undefined': `error`,
			'no-underscore-dangle': `error`,
			'no-unmodified-loop-condition': `error`,
			'no-unneeded-ternary': `error`,
			'no-unused-expressions': `error`,
			'no-use-before-define': [`error`, `nofunc`],
			'no-useless-assignment': `off`,
			'no-useless-call': `error`,
			'no-useless-computed-key': `error`,
			'no-useless-concat': `error`,
			'no-useless-constructor': `error`,
			'no-useless-rename': `error`,
			'no-useless-return': `error`,
			'no-var': `error`,
			'no-void': `error`,
			'no-warning-comments': `error`,
			'object-shorthand': `error`,
			'operator-assignment': `error`,
			'padding-line-between-statements': `error`,
			'prefer-arrow-callback': `error`,
			'prefer-const': `error`,
			'prefer-destructuring': [
				`error`,
				{
					array: false,
				},
			],
			'prefer-exponentiation-operator': `error`,
			'prefer-numeric-literals': `error`,
			'prefer-object-spread': `error`,
			'prefer-promise-reject-errors': `error`,
			'prefer-regex-literals': `error`,
			'prefer-rest-params': `error`,
			'prefer-spread': `error`,
			'prefer-template': `error`,
			quotes: [`error`, `backtick`],
			radix: `error`,
			'require-atomic-updates': `error`,
			'require-await': `error`,
			'simple-import-sort/imports': `error`,
			'simple-import-sort/exports': `error`,
			'spaced-comment': `error`,
			strict: [`error`, `safe`],
			'symbol-description': `error`,
			'unicode-bom': `error`,
			'vars-on-top': `error`,
			'vue/block-order': [
				`error`,
				{
					order: [`template`, `style`, `script`],
				},
			],
			'vue/component-definition-name-casing': [`error`, `kebab-case`],
			'vue/component-name-in-template-casing': [`error`, `kebab-case`],
			'vue/eqeqeq': `error`,
			'vue/match-component-file-name': `error`,
			'vue/no-boolean-default': `error`,
			'vue/no-deprecated-scope-attribute': `error`,
			'vue/no-deprecated-slot-attribute': `error`,
			'vue/no-deprecated-slot-scope-attribute': `error`,
			'vue/no-empty-pattern': `error`,
			'vue/no-irregular-whitespace': `error`,
			'vue/no-mutating-props': `off`,
			'vue/no-reserved-component-names': `error`,
			'vue/no-restricted-syntax': `error`,
			'vue/no-static-inline-styles': `error`,
			'vue/no-unsupported-features': `error`,
			'vue/no-v-html': `off`,
			'vue/padding-line-between-blocks': [`error`, `always`],
			'vue/prop-name-casing': [`error`, `snake_case`],
			'vue/require-direct-export': `error`,
			'vue/static-class-names-order': `error`,
			'vue/v-slot-style': `error`,
			'vue/valid-v-bind-sync': `error`,
			'vue/valid-v-slot': `error`,
			yoda: [`error`, `always`],
		},
	},
	// Disables every rule above that fights config/prettier.config.js (indent, semi, spacing,
	// etc.) - Prettier is the formatter, ESLint is left to correctness/best-practices.
	eslintConfigPrettier,
	{
		rules: {
			quotes: [`error`, `backtick`],
		},
	},
	{
		files: [`config/**/*.js`],
		languageOptions: {
			globals: {
				...globals.node,
			},
		},
	},
];
