<?php

// See https://github.com/FriendsOfPHP/PHP-CS-Fixer for options

$finder = PhpCsFixer\Finder::create()
	->exclude('bower_components')
	->exclude('node_modules')
	->exclude('vendor')
	->in(__DIR__);

return PhpCsFixer\Config::create()
	->setUsingCache(true)
	->setRiskyAllowed(true)
	->setIndent("\t")
	->setRules(
		array(
			'align_multiline_comment' => true,
			'array_indentation'       => true,
			'array_syntax'            => true,
			'backtick_to_shell_exec'  => true,
			'binary_operator_spaces'  => array(
				'default' => 'align_single_space_minimal',
			),
			'blank_line_after_namespace'   => true,
			'blank_line_after_opening_tag' => true,
			'blank_line_before_return'     => true,
			'blank_line_before_statement'  => true,
			//			'braces'                       => false,
			'cast_spaces'                 => true,
			'class_attributes_separation' => true,
			'class_definition'            => false,
			'class_keyword_remove'        => true,
			'combine_consecutive_issets'  => true,
			// 'combine_consecutive_unsets'  => true,
			'comment_to_phpdoc'         => true,
			'compact_nullable_typehint' => true,
			'concat_space'              => array(
				'spacing' => 'one',
			),
			'date_time_immutable'     => true,
			'declare_equal_normalize' => true,
			'declare_strict_types'    => false,
			'dir_constant'            => true,
			'elseif'                  => true,
			'encoding'                => true,
			'ereg_to_preg'            => true,
			'error_suppression'       => array(
				'mute_deprecation_error' => false,
				'noise_remaining_usages' => true,
			),
			'escape_implicit_backslashes'      => true,
			'explicit_indirect_variable'       => true,
			'explicit_string_variable'         => true,
			'final_internal_class'             => true,
			'full_opening_tag'                 => true,
			'fully_qualified_strict_types'     => true,
			'function_declaration'             => true,
			'function_to_constant'             => true,
			'function_typehint_space'          => true,
			'general_phpdoc_annotation_remove' => true,
			'hash_to_slash_comment'            => true,
			// header_comment
			'heredoc_to_nowdoc'                      => true,
			'include'                                => true,
			'increment_style'                        => true,
			'indentation_type'                       => true,
			'is_null'                                => true,
			'line_ending'                            => true,
			'linebreak_after_opening_tag'            => true,
			'list_syntax'                            => true,
			'logical_operators'                      => true,
			'lowercase_cast'                         => true,
			'lowercase_constants'                    => true,
			'lowercase_keywords'                     => true,
			'lowercase_static_reference'             => true,
			'magic_constant_casing'                  => true,
			'mb_str_functions'                       => true,
			'method_argument_space'                  => true,
			'method_chaining_indentation'            => true,
			'method_separation'                      => true,
			'modernize_types_casting'                => true,
			'multiline_comment_opening_closing'      => true,
			'multiline_whitespace_before_semicolons' => true,
			'native_constant_invocation'             => true,
			'native_function_casing'                 => true,
			'native_function_invocation'             => array(
				'scope'  => 'namespaced',
				'strict' => true,
			),
			'new_with_braces'                             => true,
			'no_alias_functions'                          => true,
			'no_alternative_syntax'                       => true,
			'no_binary_string'                            => true,
			'no_blank_lines_after_class_opening'          => true,
			'no_blank_lines_after_phpdoc'                 => true,
			'no_blank_lines_before_namespace'             => false,
			'no_break_comment'                            => true,
			'no_closing_tag'                              => true,
			'no_empty_comment'                            => true,
			'no_empty_phpdoc'                             => true,
			'no_empty_statement'                          => true,
			'no_extra_consecutive_blank_lines'            => true,
			'no_homoglyph_names'                          => true,
			'no_leading_import_slash'                     => true,
			'no_leading_namespace_whitespace'             => true,
			'no_mixed_echo_print'                         => true,
			'no_multiline_whitespace_around_double_arrow' => true,
			'no_multiline_whitespace_before_semicolons'   => true,
			'no_null_property_initialization'             => true,
			'no_php4_constructor'                         => true,
			'no_short_bool_cast'                          => true,
			'no_short_echo_tag'                           => true,
			'no_singleline_whitespace_before_semicolons'  => true,
			'no_spaces_after_function_name'               => true,
			'no_spaces_around_offset'                     => false,
			'no_spaces_inside_parenthesis'                => false,
			'no_superfluous_elseif'                       => true,
			'no_superfluous_phpdoc_tags'                  => true,
			'no_trailing_comma_in_list_call'              => true,
			'no_trailing_comma_in_singleline_array'       => true,
			'no_trailing_whitespace'                      => true,
			'no_trailing_whitespace_in_comment'           => true,
			'no_unneeded_control_parentheses'             => true,
			'no_unneeded_curly_braces'                    => true,
			'no_unneeded_final_method'                    => true,
			'no_unreachable_default_argument_value'       => true,
			'no_unset_on_property'                        => true,
			'no_unused_imports'                           => true,
			'no_useless_else'                             => true,
			'no_useless_return'                           => true,
			'no_whitespace_before_comma_in_array'         => true,
			'no_whitespace_in_blank_line'                 => true,
			'non_printable_character'                     => true,
			'normalize_index_brace'                       => true,
			'not_operator_with_space'                     => false,
			'not_operator_with_successor_space'           => false,
			'object_operator_without_whitespace'          => true,
			'ordered_class_elements'                      => false,
			'ordered_imports'                             => true,
			'phpdoc_add_missing_param_annotation'         => true,
			'phpdoc_align'                                => true,
			'phpdoc_annotation_without_dot'               => true,
			'phpdoc_indent'                               => true,
			'phpdoc_inline_tag'                           => true,
			'phpdoc_no_access'                            => true,
			'phpdoc_no_alias_tag'                         => true,
			'phpdoc_no_empty_return'                      => true,
			'phpdoc_no_package'                           => true,
			'phpdoc_no_useless_inheritdoc'                => true,
			'phpdoc_order'                                => true,
			'phpdoc_return_self_reference'                => true,
			'phpdoc_scalar'                               => true,
			'phpdoc_separation'                           => true,
			'phpdoc_single_line_var_spacing'              => true,
			'phpdoc_summary'                              => true,
			'phpdoc_to_comment'                           => true,
			// phpdoc_to_return_type
			'phpdoc_trim'                                   => true,
			'phpdoc_trim_consecutive_blank_line_separation' => true,
			'phpdoc_types'                                  => true,
			'phpdoc_types_order'                            => true,
			'phpdoc_var_without_name'                       => true,
			'pow_to_exponentiation'                         => true,
			'pre_increment'                                 => true,
			'protected_to_private'                          => true,
			'psr0'                                          => false,
			'psr4'                                          => false,
			'random_api_migration'                          => true,
			'return_assignment'                             => true,
			'return_type_declaration'                       => true,
			'self_accessor'                                 => true,
			'semicolon_after_instruction'                   => true,
			'set_type_to_cast'                              => true,
			'short_scalar_cast'                             => true,
			'silenced_deprecation_error'                    => true,
			'simplified_null_return'                        => true,
			'single_blank_line_at_eof'                      => true,
			'single_blank_line_before_namespace'            => true,
			'single_class_element_per_statement'            => true,
			'single_import_per_statement'                   => true,
			'single_line_after_imports'                     => true,
			'single_line_comment_style'                     => false,
			'single_quote'                                  => true,
			'space_after_semicolon'                         => true,
			'standardize_not_equals'                        => true,
			'static_lambda'                                 => true,
			'strict_comparison'                             => true,
			'strict_param'                                  => true,
			'string_line_ending'                            => true,
			'switch_case_semicolon_to_colon'                => true,
			'switch_case_space'                             => true,
			'ternary_operator_spaces'                       => true,
			'ternary_to_null_coalescing'                    => false,
			'trailing_comma_in_multiline_array'             => true,
			'trim_array_spaces'                             => true,
			'unary_operator_spaces'                         => true,
			'visibility_required'                           => true,
			'void_return'                                   => false,
			'whitespace_after_comma_in_array'               => true,
			'yoda_style'                                    => false,
		)
	)
	->setFinder($finder);
